# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

permalink: /:title/


gems:
  - jekyll-paginate
  - github-pages
  - jekyll-gist
  - jemoji


paginate: 5
paginate_path: "page:num"



markdown:     kramdown




kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
  default_lang: python
  syntax_highlighter: rouge
  

title: dongsamb.com
url: http://dongsamb.com
locale: ko_KR
avatar: /images/dongsamb.png
fb_admins: http://facebook.com/dongsam

author:
    facebook: dongsam
    twitter: dongsamb
    github: dongsam
    linkedin: dongsamb



# markdown:     redcarpet

# redcarpet:
#   extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
# redcarpet:
#     extensions: 
#       - no_intra_emphasis
#       - fenced_code_blocks
#       - tables
#       - strikethrough
#       - superscript
#       - autolink
#       - hard_wrap
#       - with_toc_data
#       - smart
# highlighter: pygments