# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: pygments
lsi: false

permalink: /:title

# markdown:     kramdown
markdown:     redcarpet

# redcarpet:
#   extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
      - with_toc_data
      - smart

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# redcarpet:
#    extensions: ["smart"]

gems:
  - jemoji

paginate: 10

title: dongsamb.com
url: http://dongsamb.com
locale: ko_KR
avatar: /images/dongsamb.png
fb_admins: http://facebook.com/dongsam

author:
    facebook: dongsam
    twitter: dongsamb
    github: dongsam
    linkedin: dongsamb